apiVersion: apps/v1
kind: Deployment
metadata:
  name: rick-and-morty-app-deployment
  labels:
    app: rick-and-morty-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rick-and-morty-app
  template:
    metadata:
      labels:
        app: rick-and-morty-app
    spec:
      containers:
      - name: rick-and-morty-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}  # or use "Never" if you're sure the image is always built locally
        ports:
        - containerPort: 5000