apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rick-and-morty-app-ingress
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rick-and-morty-app-service
            port:
              number: {{ .Values.service.port }}