apiVersion: v1
kind: Service
metadata:
  name: rick-and-morty-app-service
spec:
  selector:
    app: rick-and-morty-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}